Viktor Onegin/MediaGallery/Components/BreadcrumbViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MediaGallery.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Microsoft.EntityFrameworkCore;

namespace MediaGallery.Components
{
    public class BreadcrumbViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _dataContext;
        private readonly GalleryContext _galleryContext;

        public BreadcrumbViewComponent(ApplicationDbContext dataContext,
                                       GalleryContext galleryContext)
        {
            _dataContext = dataContext;
            _galleryContext = galleryContext;
        }

        public async Task<ViewViewComponentResult> InvokeAsync()
        {
            var items = new Dictionary<int, string>();

            if(_galleryContext.CurrentItem != null)
            {
                var item = GetWithParent(_galleryContext.CurrentItem.Id);
                if (item.ParentFolder != null)
                {
                    var parent = GetWithParent(item.ParentFolder.Id);

                    while (parent != null)
                    {
                        items.Add(parent.Id, parent.Title);

                        if (parent.ParentFolder == null)
                        {
                            break;
                        }

                        parent = GetWithParent(parent.ParentFolder.Id);
                    }
                }
            }

            items = items.Reverse().ToDictionary(k => k.Key, v => v.Value);

            return View("Index", items);
        }

        private MediaItem GetWithParent(int id)
        {
            return _dataContext.Items
                               .Include(f => f.ParentFolder)
                               .FirstOrDefault(f => f.Id == id);
        }
    }
}

Viktor Onegin/MediaGallery/Components/GalleryMenuViewComponent.cs
using System.Linq;
using System.Threading.Tasks;
using MediaGallery.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Microsoft.EntityFrameworkCore;

namespace MediaGallery.Components
{
    public class GalleryMenuViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _dataContext;

        public GalleryMenuViewComponent(ApplicationDbContext dataContext)
        {
            _dataContext = dataContext;
        }

        public async Task<ViewViewComponentResult> InvokeAsync(MediaFolder parentFolder = null)
        {
            _dataContext.Folders.ToList();

            IQueryable<MediaFolder> folders = _dataContext.Folders;
            if(parentFolder == null)
            {
                folders = folders.Where(f => f.ParentFolder == null);
            }
            else
            {
                folders = folders.Where(f => f.ParentFolder.Id == parentFolder.Id);
            }

            folders = folders.OrderBy(f => f.Title);

            return View("Index", folders.ToList());
        }
    }
}

Viktor Onegin/MediaGallery/Views/Shared/_ItemsList.cshtml
@model IEnumerable<MediaGallery.Data.MediaItem>
@inject GalleryContext _context;

<div class="row product-list">
    @foreach (var item in Model)
    {
        var routeData = new Dictionary<string, string>
        {
            { "id", item.Id.ToString() }
        };
        <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="product-item">
                <div class="pi-img-wrapper">
                    <a asp-controller="Home" asp-action="Details" asp-all-route-data="@routeData"><img src="@Url.Content(_context.GetItemUrl(item))" class="img-responsive" style="height:200px" alt="@item.Title"></a>
                </div>
                <h3><a asp-controller="Home" asp-action="Details" asp-all-route-data="@routeData">@item.Title</a></h3>
            </div>
        </div>
    }
</div>

Viktor Onegin/MediaGallery/Views/Shared/_Layout.cshtml
@inject GalleryContext _galleryContext
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>@_galleryContext.GetFullPageTitle()</title>

    <!-- Fonts START -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|PT+Sans+Narrow|Source+Sans+Pro:200,300,400,600,700,900&amp;subset=all" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900&amp;subset=all" rel="stylesheet" type="text/css"><!--- fonts for slider on the index page -->
    <!-- Fonts END -->
    <!-- Global styles START -->
    <link href="~/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Global styles END -->
    <!-- Page level plugin styles START -->
    <link href="~/assets/pages/css/animate.css" rel="stylesheet">
    <link href="~/assets/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet">
    <link href="~/assets/plugins/owl.carousel/assets/owl.carousel.css" rel="stylesheet">
    <!-- Page level plugin styles END -->
    <!-- Theme styles START -->
    <link href="~/assets/pages/css/components.css" rel="stylesheet">
    <link href="~/assets/pages/css/slider.css" rel="stylesheet">
    <link href="~/assets/pages/css/style-shop.css" rel="stylesheet" type="text/css">
    <link href="~/assets/corporate/css/style.css" rel="stylesheet">
    <link href="~/assets/corporate/css/style-responsive.css" rel="stylesheet">
    <link href="~/assets/corporate/css/themes/red.css" rel="stylesheet" id="style-color">
    <link href="~/assets/corporate/css/custom.css" rel="stylesheet">

    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />*@

</head>
<body class="ecommerce">

    <!-- BEGIN TOP BAR -->
    <div class="pre-header">
        <div class="container">
            <div class="row">
                <!-- BEGIN TOP BAR LEFT PART -->
                <div class="col-md-6 col-sm-6 additional-shop-info">
                    <ul class="list-unstyled list-inline">
                        <li><i class="fa fa-phone"></i><span>+1 456 6717</span></li>
                    </ul>
                </div>
                <!-- END TOP BAR LEFT PART -->
                <!-- BEGIN TOP BAR MENU -->
                <div class="col-md-6 col-sm-6 additional-nav">
                    <ul class="list-unstyled list-inline pull-right">
                        <li><a href="shop-account.html">My Account</a></li>
                        <li><a href="shop-wishlist.html">My Wishlist</a></li>
                        <li><a href="shop-checkout.html">Checkout</a></li>
                        <li><a href="page-login.html">Log In</a></li>
                    </ul>
                </div>
                <!-- END TOP BAR MENU -->
            </div>
        </div>
    </div>
    <!-- END TOP BAR -->
    <!-- BEGIN HEADER -->
    <div class="header">
        <div class="container">
            <a class="site-logo" href="shop-index.html"><img src="assets/corporate/img/logos/logo-shop-red.png" alt="Metronic Shop UI"></a>
            <a href="javascript:void(0);" class="mobi-toggler"><i class="fa fa-bars"></i></a>
            <!-- BEGIN NAVIGATION -->
            <div class="header-navigation">
                <ul>
                    <li><a href="@Url.Action("CreateFolder", new { parentFolder = _galleryContext.GetCurrentFolderId() })">Lisa kaust</a></li>
                    <li><a href="@Url.Action("UploadFile", new { parentFolder = _galleryContext.GetCurrentFolderId() })">Lisa fail</a></li>

                    <!-- BEGIN TOP SEARCH -->
                    <li class="menu-search">
                        <span class="sep"></span>
                        <i class="fa fa-search search-btn"></i>
                        <div class="search-box">
                            <form action="#">
                                <div class="input-group">
                                    <input type="text" placeholder="Search" class="form-control">
                                    <span class="input-group-btn">
                                        <button class="btn btn-primary" type="submit">Search</button>
                                    </span>
                                </div>
                            </form>
                        </div>
                    </li>
                    <!-- END TOP SEARCH -->
                </ul>
            </div>
            <!-- END NAVIGATION -->
        </div>
    </div>
    <!-- Header END -->

    <div class="container">
        <div class="row">
            <div class="sidebar col-md-3 col-sm-5">
                @await Component.InvokeAsync("Breadcrumb")
            </div>
        </div>
    </div>

    @RenderBody()

    <!-- BEGIN FOOTER -->
    <div class="footer">
        <div class="container">
            <div class="row">
                <!-- BEGIN COPYRIGHT -->
                <div class="col-md-4 col-sm-4 padding-top-10">
                    2015 © Keenthemes. ALL Rights Reserved.
                </div>
                <!-- END COPYRIGHT -->
                <!-- BEGIN PAYMENTS -->
                <div class="col-md-4 col-sm-4">

                </div>
                <!-- END PAYMENTS -->
                <!-- BEGIN POWERED -->
                <div class="col-md-4 col-sm-4 text-right">
                    <p class="powered">Powered by: <a href="http://www.keenthemes.com/">KeenThemes.com</a></p>
                </div>
                <!-- END POWERED -->
            </div>
        </div>
    </div>
    <!-- END FOOTER -->
    @*<nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MediaGallery</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>*@

    @*<div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2018 - MediaGallery</p>
            </footer>
        </div>

        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

        @RenderSection("Scripts", required: false)*@

    <script src="@Url.Content("~/assets/plugins/jquery.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/assets/plugins/jquery-migrate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/assets/plugins/bootstrap/js/bootstrap.min.js")" type="text/javascript"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Viktor Onegin/MediaGallery/Views/Shared/_Sidebar.cshtml
<!-- BEGIN SIDEBAR -->
<div class="sidebar margin-bottom-25 col-md-3 col-sm-5 sidebar-menu">
    @await Component.InvokeAsync("GalleryMenu")
</div>
<!-- END SIDEBAR -->